# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.26.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.26.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/antoine7805/Developer/ProjetTI202

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/antoine7805/Developer/ProjetTI202

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.26.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.26.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/antoine7805/Developer/ProjetTI202/CMakeFiles /Users/antoine7805/Developer/ProjetTI202//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/antoine7805/Developer/ProjetTI202/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ProjetTI202

# Build rule for target.
ProjetTI202: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ProjetTI202
.PHONY : ProjetTI202

# fast build rule for target.
ProjetTI202/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/build
.PHONY : ProjetTI202/fast

algorithm.o: algorithm.c.o
.PHONY : algorithm.o

# target to build an object file
algorithm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/algorithm.c.o
.PHONY : algorithm.c.o

algorithm.i: algorithm.c.i
.PHONY : algorithm.i

# target to preprocess a source file
algorithm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/algorithm.c.i
.PHONY : algorithm.c.i

algorithm.s: algorithm.c.s
.PHONY : algorithm.s

# target to generate assembly for a file
algorithm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/algorithm.c.s
.PHONY : algorithm.c.s

chained_list.o: chained_list.c.o
.PHONY : chained_list.o

# target to build an object file
chained_list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/chained_list.c.o
.PHONY : chained_list.c.o

chained_list.i: chained_list.c.i
.PHONY : chained_list.i

# target to preprocess a source file
chained_list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/chained_list.c.i
.PHONY : chained_list.c.i

chained_list.s: chained_list.c.s
.PHONY : chained_list.s

# target to generate assembly for a file
chained_list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/chained_list.c.s
.PHONY : chained_list.c.s

geometry.o: geometry.c.o
.PHONY : geometry.o

# target to build an object file
geometry.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/geometry.c.o
.PHONY : geometry.c.o

geometry.i: geometry.c.i
.PHONY : geometry.i

# target to preprocess a source file
geometry.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/geometry.c.i
.PHONY : geometry.c.i

geometry.s: geometry.c.s
.PHONY : geometry.s

# target to generate assembly for a file
geometry.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/geometry.c.s
.PHONY : geometry.c.s

id.o: id.c.o
.PHONY : id.o

# target to build an object file
id.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/id.c.o
.PHONY : id.c.o

id.i: id.c.i
.PHONY : id.i

# target to preprocess a source file
id.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/id.c.i
.PHONY : id.c.i

id.s: id.c.s
.PHONY : id.s

# target to generate assembly for a file
id.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/id.c.s
.PHONY : id.c.s

keyboard.o: keyboard.c.o
.PHONY : keyboard.o

# target to build an object file
keyboard.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/keyboard.c.o
.PHONY : keyboard.c.o

keyboard.i: keyboard.c.i
.PHONY : keyboard.i

# target to preprocess a source file
keyboard.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/keyboard.c.i
.PHONY : keyboard.c.i

keyboard.s: keyboard.c.s
.PHONY : keyboard.s

# target to generate assembly for a file
keyboard.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/keyboard.c.s
.PHONY : keyboard.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/main.c.s
.PHONY : main.c.s

menu.o: menu.c.o
.PHONY : menu.o

# target to build an object file
menu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/menu.c.o
.PHONY : menu.c.o

menu.i: menu.c.i
.PHONY : menu.i

# target to preprocess a source file
menu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/menu.c.i
.PHONY : menu.c.i

menu.s: menu.c.s
.PHONY : menu.s

# target to generate assembly for a file
menu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/menu.c.s
.PHONY : menu.c.s

utils.o: utils.c.o
.PHONY : utils.o

# target to build an object file
utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/utils.c.o
.PHONY : utils.c.o

utils.i: utils.c.i
.PHONY : utils.i

# target to preprocess a source file
utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/utils.c.i
.PHONY : utils.c.i

utils.s: utils.c.s
.PHONY : utils.s

# target to generate assembly for a file
utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetTI202.dir/build.make CMakeFiles/ProjetTI202.dir/utils.c.s
.PHONY : utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ProjetTI202"
	@echo "... algorithm.o"
	@echo "... algorithm.i"
	@echo "... algorithm.s"
	@echo "... chained_list.o"
	@echo "... chained_list.i"
	@echo "... chained_list.s"
	@echo "... geometry.o"
	@echo "... geometry.i"
	@echo "... geometry.s"
	@echo "... id.o"
	@echo "... id.i"
	@echo "... id.s"
	@echo "... keyboard.o"
	@echo "... keyboard.i"
	@echo "... keyboard.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... menu.o"
	@echo "... menu.i"
	@echo "... menu.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

