name: Windows build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run cmake
        run: cmake .

      - name: Build project
        run: cmake --build . --config Release

      - name: Publish
        # Upload the build artifact for later use as a release asset
        uses: actions/upload-artifact@v2
        with:
          name: ProjetTI202
          path: Release/ProjetTI202.exe
